import { Tweet } from "../@types/interfaces";

export const sampleTweetsWithGeo: Array<Tweet> = [
  {
    _tweetId: "1509520889477582854",
    geo: [48.90408, 38.42881],
    uuid: "1509520889477582854",
    created_at: 1509522058434162700,
    text: "In #Lysychansk , the occupiers fired at an oil storage facility, in #Severodonetsk - a school\n#war #ukraine… https://t.co/ehp2nz4Dct",
    source: "twitter",
  },
];

export const sampleTweets = [
  {
    created_at: "Thu Mar 31 13:24:38 +0000 2022",
    id: 1509522058434162700,
    id_str: "1509522058434162688",
    text: "Daughters of Serhiy Skadovsky - the founder of city of #Skadovsk, #Kherson region of #Ukraine, temporary seized by… https://t.co/vKdavxXzmd",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Skadovsk",
          indices: [55, 64],
        },
        {
          text: "Kherson",
          indices: [66, 74],
        },
        {
          text: "Ukraine",
          indices: [85, 93],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/vKdavxXzmd",
          expanded_url: "https://twitter.com/i/web/status/1509522058434162688",
          display_url: "twitter.com/i/web/status/1…",
          indices: [116, 139],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 2288308578,
      id_str: "2288308578",
      name: "EMPR.MEDIA",
      screen_name: "EuromaidanPR",
      location: "Ukraine",
      description:
        "#1 Independent Citizen Media about #Ukraine | Former Official International Public Relations Secretariat for the HQ of National Resistance of Euromaidan",
      url: "https://t.co/ptNwF4IZQX",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/ptNwF4IZQX",
              expanded_url: "https://empr.media",
              display_url: "empr.media",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 86967,
      friends_count: 3584,
      listed_count: 2559,
      created_at: "Sun Jan 12 15:28:39 +0000 2014",
      favourites_count: 3305,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 76232,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/559049235904344064/oAPU_Lvh_normal.jpeg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/559049235904344064/oAPU_Lvh_normal.jpeg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/2288308578/1398234747",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: true,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:24:20 +0000 2022",
    id: 1509521980441219000,
    id_str: "1509521980441219072",
    text: "7 busses with Russian soldiers suffering from Acute Radiation Syndrome have arrived to a hospital in #Belarus from… https://t.co/MGrfT2cHSY",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Belarus",
          indices: [101, 109],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/MGrfT2cHSY",
          expanded_url: "https://twitter.com/i/web/status/1509521980441219072",
          display_url: "twitter.com/i/web/status/1…",
          indices: [116, 139],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1222084828100776000,
      id_str: "1222084828100775945",
      name: "The Odessa Journal 🖋⚓",
      screen_name: "Odessa_Journal",
      location: "Odessa, Ukraine",
      description:
        "THE ENGLISH VOICE OF ODESSA\n#Odessa #Ukraine  ☦✡☪🎨🎼📖🎥💋\n\nHELP THE WORK OF OUR EDITORIAL TEAM !\nBecome our PATRON: https://t.co/dUQDPU6mBa",
      url: "https://t.co/jwDRRuID1R",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/jwDRRuID1R",
              expanded_url: "http://www.odessa-journal.com",
              display_url: "odessa-journal.com",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [
            {
              url: "https://t.co/dUQDPU6mBa",
              expanded_url: "https://www.patreon.com/the_odessa_journal",
              display_url: "patreon.com/the_odessa_jou…",
              indices: [113, 136],
            },
          ],
        },
      },
      protected: false,
      followers_count: 4353,
      friends_count: 586,
      listed_count: 112,
      created_at: "Tue Jan 28 09:12:51 +0000 2020",
      favourites_count: 933,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 2411,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1222088414683705344/cFCyWMZ3_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1222088414683705344/cFCyWMZ3_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1222084828100775945/1580206764",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 2,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:20:24 +0000 2022",
    id: 1509520991046623200,
    id_str: "1509520991046623234",
    text: "⚡️🇬🇧 “The decision on the procedure for paying for gas supplies in rubles is a step towards the financial sovereign… https://t.co/VjDpiwZF69",
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/VjDpiwZF69",
          expanded_url: "https://twitter.com/i/web/status/1509520991046623234",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://example.com" rel="nofollow">TelegramUKRWarSitrep</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1497262491436519400,
      id_str: "1497262491436519436",
      name: "Ukraine War SitRep 🇺🇦",
      screen_name: "UKRWarSitRep",
      location: "Ukraine",
      description:
        "Reposting verified media only about the Ukraine invasion by Putin.\n\nTranslating for English audience.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 5083,
      friends_count: 1,
      listed_count: 106,
      created_at: "Fri Feb 25 17:29:54 +0000 2022",
      favourites_count: 13,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1645,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1497262491436519436/1645810645",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:20:20 +0000 2022",
    id: 1509520973132968000,
    id_str: "1509520973132967938",
    text: "⚡#Russian military in #Ukraine accidentally shot down their own plane - #British intelligence.🤡… https://t.co/P4WrrSFlju",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Russian",
          indices: [1, 9],
        },
        {
          text: "Ukraine",
          indices: [22, 30],
        },
        {
          text: "British",
          indices: [72, 80],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/P4WrrSFlju",
          expanded_url: "https://twitter.com/i/web/status/1509520973132967938",
          display_url: "twitter.com/i/web/status/1…",
          indices: [97, 120],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 44906101,
      id_str: "44906101",
      name: "THIS.IS.UKRAINE🇺🇦",
      screen_name: "THIS_IS_UKR",
      location: "Украина",
      description: "Glory to The Heroes. Slava Ukraini!✊🇺🇦",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 1144,
      friends_count: 108,
      listed_count: 85,
      created_at: "Fri Jun 05 14:42:09 +0000 2009",
      favourites_count: 442,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 9381,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "000000",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme2/bg.gif",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme2/bg.gif",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1505959538721271812/UK52MvAZ_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1505959538721271812/UK52MvAZ_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/44906101/1647884431",
      profile_link_color: "CC3300",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "F7DA93",
      profile_text_color: "000000",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:20:00 +0000 2022",
    id: 1509520889477582800,
    id_str: "1509520889477582854",
    text: "In #Lysychansk , the occupiers fired at an oil storage facility, in #Severodonetsk - a school\n#war #ukraine… https://t.co/ehp2nz4Dct",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Lysychansk",
          indices: [3, 14],
        },
        {
          text: "Severodonetsk",
          indices: [68, 82],
        },
        {
          text: "war",
          indices: [94, 98],
        },
        {
          text: "ukraine",
          indices: [99, 107],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/ehp2nz4Dct",
          expanded_url: "https://twitter.com/i/web/status/1509520889477582854",
          display_url: "twitter.com/i/web/status/1…",
          indices: [109, 132],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1501094969108570000,
      id_str: "1501094969108570114",
      name: "UKRAINENOW",
      screen_name: "UKRAINENOWphoto",
      location: "Украина",
      description: "War in Ukraine. Here and now.\n#war #ukraine #russia",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 154,
      friends_count: 2,
      listed_count: 1,
      created_at: "Tue Mar 08 07:18:33 +0000 2022",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 421,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1501096313768878081/MTJaO63M_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1501096313768878081/MTJaO63M_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1501094969108570114/1646748778",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:19:01 +0000 2022",
    id: 1509520642160402400,
    id_str: "1509520642160402442",
    text: "#Ukrain #Ukraine #UkraineRussianWar #UkraineWar \nThose are anti-tank mines https://t.co/G7U2hxGA14",
    truncated: false,
    entities: {
      hashtags: [
        {
          text: "Ukrain",
          indices: [0, 7],
        },
        {
          text: "Ukraine",
          indices: [8, 16],
        },
        {
          text: "UkraineRussianWar",
          indices: [17, 35],
        },
        {
          text: "UkraineWar",
          indices: [36, 47],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [],
      media: [
        {
          id: 1509520485759000600,
          id_str: "1509520485759000576",
          indices: [75, 98],
          media_url:
            "http://pbs.twimg.com/ext_tw_video_thumb/1509520485759000576/pu/img/xe2ExedSsCSJrMFy.jpg",
          media_url_https:
            "https://pbs.twimg.com/ext_tw_video_thumb/1509520485759000576/pu/img/xe2ExedSsCSJrMFy.jpg",
          url: "https://t.co/G7U2hxGA14",
          display_url: "pic.twitter.com/G7U2hxGA14",
          expanded_url:
            "https://twitter.com/roflchatgroup/status/1509520642160402442/video/1",
          type: "photo",
          sizes: {
            thumb: {
              w: 150,
              h: 150,
              resize: "crop",
            },
            small: {
              w: 383,
              h: 680,
              resize: "fit",
            },
            large: {
              w: 720,
              h: 1280,
              resize: "fit",
            },
            medium: {
              w: 675,
              h: 1200,
              resize: "fit",
            },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1509520485759000600,
          id_str: "1509520485759000576",
          indices: [75, 98],
          media_url:
            "http://pbs.twimg.com/ext_tw_video_thumb/1509520485759000576/pu/img/xe2ExedSsCSJrMFy.jpg",
          media_url_https:
            "https://pbs.twimg.com/ext_tw_video_thumb/1509520485759000576/pu/img/xe2ExedSsCSJrMFy.jpg",
          url: "https://t.co/G7U2hxGA14",
          display_url: "pic.twitter.com/G7U2hxGA14",
          expanded_url:
            "https://twitter.com/roflchatgroup/status/1509520642160402442/video/1",
          type: "video",
          sizes: {
            thumb: {
              w: 150,
              h: 150,
              resize: "crop",
            },
            small: {
              w: 383,
              h: 680,
              resize: "fit",
            },
            large: {
              w: 720,
              h: 1280,
              resize: "fit",
            },
            medium: {
              w: 675,
              h: 1200,
              resize: "fit",
            },
          },
          video_info: {
            aspect_ratio: [9, 16],
            duration_millis: 89303,
            variants: [
              {
                content_type: "application/x-mpegURL",
                url: "https://video.twimg.com/ext_tw_video/1509520485759000576/pu/pl/9QkGn4uzgxyXX2RA.m3u8?tag=12&container=fmp4",
              },
              {
                bitrate: 950000,
                content_type: "video/mp4",
                url: "https://video.twimg.com/ext_tw_video/1509520485759000576/pu/vid/480x852/t74ccl_n04nYEH1b.mp4?tag=12",
              },
              {
                bitrate: 2176000,
                content_type: "video/mp4",
                url: "https://video.twimg.com/ext_tw_video/1509520485759000576/pu/vid/720x1280/zEq6L2itw6BQvmFR.mp4?tag=12",
              },
              {
                bitrate: 632000,
                content_type: "video/mp4",
                url: "https://video.twimg.com/ext_tw_video/1509520485759000576/pu/vid/320x568/JYJwTrj1pDH1k5D7.mp4?tag=12",
              },
            ],
          },
          additional_media_info: {
            monetizable: false,
          },
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1499007542147571700,
      id_str: "1499007542147571720",
      name: "RoflChatGroup",
      screen_name: "roflchatgroup",
      location: "Ukraine",
      description:
        "Вирішив зайти та кидати сюди різні відео та фото з України. Просто так.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 607,
      friends_count: 48,
      listed_count: 12,
      created_at: "Wed Mar 02 13:04:04 +0000 2022",
      favourites_count: 686,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 678,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1499007631519891463/AUkvWlDy_normal.png",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1499007631519891463/AUkvWlDy_normal.png",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1499007542147571720/1647103437",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:18:14 +0000 2022",
    id: 1509520444982198300,
    id_str: "1509520444982198274",
    text: "Such is life in Kharkiv and many Ukrainian cities right now, never again is now.\n\n#Ukraine https://t.co/Zk58JQb0WV",
    truncated: false,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [82, 90],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [],
      media: [
        {
          id: 1509520254359457800,
          id_str: "1509520254359457799",
          indices: [91, 114],
          media_url: "http://pbs.twimg.com/media/FPLkrG5aUAce-Jp.jpg",
          media_url_https: "https://pbs.twimg.com/media/FPLkrG5aUAce-Jp.jpg",
          url: "https://t.co/Zk58JQb0WV",
          display_url: "pic.twitter.com/Zk58JQb0WV",
          expanded_url:
            "https://twitter.com/Nezhaleznist/status/1509520444982198274/photo/1",
          type: "photo",
          sizes: {
            thumb: {
              w: 150,
              h: 150,
              resize: "crop",
            },
            large: {
              w: 1170,
              h: 1147,
              resize: "fit",
            },
            small: {
              w: 680,
              h: 667,
              resize: "fit",
            },
            medium: {
              w: 1170,
              h: 1147,
              resize: "fit",
            },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1509520254359457800,
          id_str: "1509520254359457799",
          indices: [91, 114],
          media_url: "http://pbs.twimg.com/media/FPLkrG5aUAce-Jp.jpg",
          media_url_https: "https://pbs.twimg.com/media/FPLkrG5aUAce-Jp.jpg",
          url: "https://t.co/Zk58JQb0WV",
          display_url: "pic.twitter.com/Zk58JQb0WV",
          expanded_url:
            "https://twitter.com/Nezhaleznist/status/1509520444982198274/photo/1",
          type: "photo",
          sizes: {
            thumb: {
              w: 150,
              h: 150,
              resize: "crop",
            },
            large: {
              w: 1170,
              h: 1147,
              resize: "fit",
            },
            small: {
              w: 680,
              h: 667,
              resize: "fit",
            },
            medium: {
              w: 1170,
              h: 1147,
              resize: "fit",
            },
          },
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1438386738884329500,
      id_str: "1438386738884329472",
      name: "Nezhaleznist 🇺🇦",
      screen_name: "Nezhaleznist",
      location: "Ukraine",
      description:
        "Independence and Sovereignty for Ukraine 🇺🇦\n\nTo donate to our heroes please visit\nhttps://t.co/uZahwffdR4",
      url: null,
      entities: {
        description: {
          urls: [
            {
              url: "https://t.co/uZahwffdR4",
              expanded_url: "https://www.comebackalive.in.ua/",
              display_url: "comebackalive.in.ua",
              indices: [82, 105],
            },
          ],
        },
      },
      protected: false,
      followers_count: 129,
      friends_count: 2,
      listed_count: 3,
      created_at: "Thu Sep 16 06:19:13 +0000 2021",
      favourites_count: 1,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 370,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1500873155908288515/ieWqVIbE_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1500873155908288515/ieWqVIbE_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1438386738884329472/1646567521",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:17:31 +0000 2022",
    id: 1509520265046376400,
    id_str: "1509520265046376449",
    text: "⚡️🇬🇧 Current gas supply contracts will be stopped if buyers from unfriendly countries do not comply with new paymen… https://t.co/14Mz3eJpyH",
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/14Mz3eJpyH",
          expanded_url: "https://twitter.com/i/web/status/1509520265046376449",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://example.com" rel="nofollow">TelegramUKRWarSitrep</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1497262491436519400,
      id_str: "1497262491436519436",
      name: "Ukraine War SitRep 🇺🇦",
      screen_name: "UKRWarSitRep",
      location: "Ukraine",
      description:
        "Reposting verified media only about the Ukraine invasion by Putin.\n\nTranslating for English audience.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 5083,
      friends_count: 1,
      listed_count: 106,
      created_at: "Fri Feb 25 17:29:54 +0000 2022",
      favourites_count: 13,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1645,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1497262491436519436/1645810645",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:16:31 +0000 2022",
    id: 1509520014096969700,
    id_str: "1509520014096969736",
    text: "A huge tragedy happened in Perm - the price of cocaine and mephedrone rose sharply there. How do Permians live now?… https://t.co/cKJx2xN4qm",
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/cKJx2xN4qm",
          expanded_url: "https://twitter.com/i/web/status/1509520014096969736",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://example.com" rel="nofollow">TelegramUKRWarSitrep</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1497262491436519400,
      id_str: "1497262491436519436",
      name: "Ukraine War SitRep 🇺🇦",
      screen_name: "UKRWarSitRep",
      location: "Ukraine",
      description:
        "Reposting verified media only about the Ukraine invasion by Putin.\n\nTranslating for English audience.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 5083,
      friends_count: 1,
      listed_count: 106,
      created_at: "Fri Feb 25 17:29:54 +0000 2022",
      favourites_count: 13,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1645,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1497262491436519436/1645810645",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:16:24 +0000 2022",
    id: 1509519984221102000,
    id_str: "1509519984221102080",
    text: "⚡️🇬🇧 Putin announced that he signed a decree on the rules of gas trade with unfriendly countries #Ukraine… https://t.co/9WTlC4oayo",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [97, 105],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/9WTlC4oayo",
          expanded_url: "https://twitter.com/i/web/status/1509519984221102080",
          display_url: "twitter.com/i/web/status/1…",
          indices: [107, 130],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://example.com" rel="nofollow">TelegramUKRWarSitrep</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1497262491436519400,
      id_str: "1497262491436519436",
      name: "Ukraine War SitRep 🇺🇦",
      screen_name: "UKRWarSitRep",
      location: "Ukraine",
      description:
        "Reposting verified media only about the Ukraine invasion by Putin.\n\nTranslating for English audience.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 5083,
      friends_count: 1,
      listed_count: 106,
      created_at: "Fri Feb 25 17:29:54 +0000 2022",
      favourites_count: 13,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1645,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1497262491436519436/1645810645",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:15:24 +0000 2022",
    id: 1509519732252237800,
    id_str: "1509519732252237828",
    text: "⚡️ After Zelensky&amp;#39;s speech, Australia introduces a duty and refuses oil and gas from Russia. Real War #Ukraine… https://t.co/orTDgEfUl4",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [110, 118],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/orTDgEfUl4",
          expanded_url: "https://twitter.com/i/web/status/1509519732252237828",
          display_url: "twitter.com/i/web/status/1…",
          indices: [120, 143],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://example.com" rel="nofollow">TelegramUKRWarSitrep</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1497262491436519400,
      id_str: "1497262491436519436",
      name: "Ukraine War SitRep 🇺🇦",
      screen_name: "UKRWarSitRep",
      location: "Ukraine",
      description:
        "Reposting verified media only about the Ukraine invasion by Putin.\n\nTranslating for English audience.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 5083,
      friends_count: 1,
      listed_count: 106,
      created_at: "Fri Feb 25 17:29:54 +0000 2022",
      favourites_count: 13,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1645,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1497262491436519436/1645810645",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:15:00 +0000 2022",
    id: 1509519631471493000,
    id_str: "1509519631471493130",
    text: "@RepClayHiggins #Ukraine #UkraineWar CALLS FOR RED CROSS BOYCOTT due to leadership cozy approving relationships wit… https://t.co/ZDG4Cu2haH",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [16, 24],
        },
        {
          text: "UkraineWar",
          indices: [25, 36],
        },
      ],
      symbols: [],
      user_mentions: [
        {
          screen_name: "RepClayHiggins",
          name: "Rep. Clay Higgins",
          id: 843636970538618900,
          id_str: "843636970538618880",
          indices: [0, 15],
        },
      ],
      urls: [
        {
          url: "https://t.co/ZDG4Cu2haH",
          expanded_url: "https://twitter.com/i/web/status/1509519631471493130",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1509172051722002400,
    in_reply_to_status_id_str: "1509172051722002436",
    in_reply_to_user_id: 843636970538618900,
    in_reply_to_user_id_str: "843636970538618880",
    in_reply_to_screen_name: "RepClayHiggins",
    user: {
      id: 1885712982,
      id_str: "1885712982",
      name: "Reznik Philipp",
      screen_name: "rephilz7",
      location: "Украина",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 49,
      listed_count: 0,
      created_at: "Fri Sep 20 07:48:45 +0000 2013",
      favourites_count: 2,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 101,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1885712982/1379664445",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:14:44 +0000 2022",
    id: 1509519563121209300,
    id_str: "1509519563121209349",
    text: "@RepTroyCarter #Ukraine #UkraineWar CALLS FOR RED CROSS BOYCOTT due to leadership cozy approving relationships with… https://t.co/5gYOoakr9g",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [15, 23],
        },
        {
          text: "UkraineWar",
          indices: [24, 35],
        },
      ],
      symbols: [],
      user_mentions: [
        {
          screen_name: "RepTroyCarter",
          name: "Congressman Troy A. Carter",
          id: 1352760304271241200,
          id_str: "1352760304271241218",
          indices: [0, 14],
        },
      ],
      urls: [
        {
          url: "https://t.co/5gYOoakr9g",
          expanded_url: "https://twitter.com/i/web/status/1509519563121209349",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1501588712953684000,
    in_reply_to_status_id_str: "1501588712953683971",
    in_reply_to_user_id: 1352760304271241200,
    in_reply_to_user_id_str: "1352760304271241218",
    in_reply_to_screen_name: "RepTroyCarter",
    user: {
      id: 1885712982,
      id_str: "1885712982",
      name: "Reznik Philipp",
      screen_name: "rephilz7",
      location: "Украина",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 49,
      listed_count: 0,
      created_at: "Fri Sep 20 07:48:45 +0000 2013",
      favourites_count: 2,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 101,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1885712982/1379664445",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:14:24 +0000 2022",
    id: 1509519480346615800,
    id_str: "1509519480346615815",
    text: "@SteveScalise #Ukraine #UkraineWar CALLS FOR RED CROSS BOYCOTT due to leadership cozy approving relationships with… https://t.co/jgPqQ5oCDw",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [14, 22],
        },
        {
          text: "UkraineWar",
          indices: [23, 34],
        },
      ],
      symbols: [],
      user_mentions: [
        {
          screen_name: "SteveScalise",
          name: "Steve Scalise",
          id: 1209417007,
          id_str: "1209417007",
          indices: [0, 13],
        },
      ],
      urls: [
        {
          url: "https://t.co/jgPqQ5oCDw",
          expanded_url: "https://twitter.com/i/web/status/1509519480346615815",
          display_url: "twitter.com/i/web/status/1…",
          indices: [116, 139],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1500959202478547000,
    in_reply_to_status_id_str: "1500959202478546953",
    in_reply_to_user_id: 1209417007,
    in_reply_to_user_id_str: "1209417007",
    in_reply_to_screen_name: "SteveScalise",
    user: {
      id: 1885712982,
      id_str: "1885712982",
      name: "Reznik Philipp",
      screen_name: "rephilz7",
      location: "Украина",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 49,
      listed_count: 0,
      created_at: "Fri Sep 20 07:48:45 +0000 2013",
      favourites_count: 2,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 101,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1885712982/1379664445",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:13:57 +0000 2022",
    id: 1509519367951822800,
    id_str: "1509519367951822848",
    text: "@RepWesterman #Ukraine #UkraineWar CALLS FOR RED CROSS BOYCOTT due to leadership cozy approving relationships with… https://t.co/gaECB0KfMW",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [14, 22],
        },
        {
          text: "UkraineWar",
          indices: [23, 34],
        },
      ],
      symbols: [],
      user_mentions: [
        {
          screen_name: "RepWesterman",
          name: "Rep. Bruce Westerman",
          id: 2852998461,
          id_str: "2852998461",
          indices: [0, 13],
        },
      ],
      urls: [
        {
          url: "https://t.co/gaECB0KfMW",
          expanded_url: "https://twitter.com/i/web/status/1509519367951822848",
          display_url: "twitter.com/i/web/status/1…",
          indices: [116, 139],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1415299608343892000,
    in_reply_to_status_id_str: "1415299608343891969",
    in_reply_to_user_id: 2852998461,
    in_reply_to_user_id_str: "2852998461",
    in_reply_to_screen_name: "RepWesterman",
    user: {
      id: 1885712982,
      id_str: "1885712982",
      name: "Reznik Philipp",
      screen_name: "rephilz7",
      location: "Украина",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 49,
      listed_count: 0,
      created_at: "Fri Sep 20 07:48:45 +0000 2013",
      favourites_count: 2,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 101,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/706817826351398913/KEb5UKYm_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1885712982/1379664445",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:13:42 +0000 2022",
    id: 1509519303804334000,
    id_str: "1509519303804334083",
    text: "Ukrainian heroes are warmly welcomed by residents of liberated city of Trostyanets in the Kharkiv region. \n\nGlory t… https://t.co/CT7K5dRwnO",
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/CT7K5dRwnO",
          expanded_url: "https://twitter.com/i/web/status/1509519303804334083",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1438386738884329500,
      id_str: "1438386738884329472",
      name: "Nezhaleznist 🇺🇦",
      screen_name: "Nezhaleznist",
      location: "Ukraine",
      description:
        "Independence and Sovereignty for Ukraine 🇺🇦\n\nTo donate to our heroes please visit\nhttps://t.co/uZahwffdR4",
      url: null,
      entities: {
        description: {
          urls: [
            {
              url: "https://t.co/uZahwffdR4",
              expanded_url: "https://www.comebackalive.in.ua/",
              display_url: "comebackalive.in.ua",
              indices: [82, 105],
            },
          ],
        },
      },
      protected: false,
      followers_count: 129,
      friends_count: 2,
      listed_count: 3,
      created_at: "Thu Sep 16 06:19:13 +0000 2021",
      favourites_count: 1,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 370,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1500873155908288515/ieWqVIbE_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1500873155908288515/ieWqVIbE_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1438386738884329472/1646567521",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:13:24 +0000 2022",
    id: 1509519228919025700,
    id_str: "1509519228919025670",
    text: "⚡️Putin announced that he signed a decree on gas trade with unfriendly countries. 👉 Ax Live #Ukraine #UkraineWar #Russia #UkraineInvasion",
    truncated: false,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [92, 100],
        },
        {
          text: "UkraineWar",
          indices: [101, 112],
        },
        {
          text: "Russia",
          indices: [113, 120],
        },
        {
          text: "UkraineInvasion",
          indices: [121, 137],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://example.com" rel="nofollow">TelegramUKRWarSitrep</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1497262491436519400,
      id_str: "1497262491436519436",
      name: "Ukraine War SitRep 🇺🇦",
      screen_name: "UKRWarSitRep",
      location: "Ukraine",
      description:
        "Reposting verified media only about the Ukraine invasion by Putin.\n\nTranslating for English audience.",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 5083,
      friends_count: 1,
      listed_count: 106,
      created_at: "Fri Feb 25 17:29:54 +0000 2022",
      favourites_count: 13,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1645,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1497263726919049219/VhZC7rgM_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1497262491436519436/1645810645",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:12:53 +0000 2022",
    id: 1509519097868042200,
    id_str: "1509519097868042246",
    text: "❗️ #DTEK Group, NJSC #Naftogaz of #Ukraine and NPC Ukrenergo called on Western companies to stop cooperation with… https://t.co/Vfz0Ydf2Xk",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "DTEK",
          indices: [3, 8],
        },
        {
          text: "Naftogaz",
          indices: [21, 30],
        },
        {
          text: "Ukraine",
          indices: [34, 42],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/Vfz0Ydf2Xk",
          expanded_url: "https://twitter.com/i/web/status/1509519097868042246",
          display_url: "twitter.com/i/web/status/1…",
          indices: [115, 138],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1496161188077621200,
      id_str: "1496161188077621251",
      name: "U24",
      screen_name: "u24_news",
      location: "Ukraine",
      description:
        "Watch. Know. Decide. Breaking news from Ukraine. News observation. Important information.",
      url: "https://t.co/p9DUDfaDnb",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/p9DUDfaDnb",
              expanded_url: "https://u24.ua/",
              display_url: "u24.ua",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 2142,
      friends_count: 88,
      listed_count: 34,
      created_at: "Tue Feb 22 16:33:47 +0000 2022",
      favourites_count: 71,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 3516,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1496161378742243329/OnVMz1nw_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1496161378742243329/OnVMz1nw_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1496161188077621251/1645548035",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 2,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:12:36 +0000 2022",
    id: 1509519028661989400,
    id_str: "1509519028661989390",
    text: "⚡The #Spanish government sent a total of ten aircraft with offensive weapons to #Ukraine.✊🇺🇦\n\n#UkraineUnderAttaсk… https://t.co/1KezXDS6VL",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Spanish",
          indices: [5, 13],
        },
        {
          text: "Ukraine",
          indices: [80, 88],
        },
        {
          text: "UkraineUnderAttaсk",
          indices: [94, 113],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/1KezXDS6VL",
          expanded_url: "https://twitter.com/i/web/status/1509519028661989390",
          display_url: "twitter.com/i/web/status/1…",
          indices: [115, 138],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 44906101,
      id_str: "44906101",
      name: "THIS.IS.UKRAINE🇺🇦",
      screen_name: "THIS_IS_UKR",
      location: "Украина",
      description: "Glory to The Heroes. Slava Ukraini!✊🇺🇦",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 1144,
      friends_count: 108,
      listed_count: 85,
      created_at: "Fri Jun 05 14:42:09 +0000 2009",
      favourites_count: 442,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 9381,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "000000",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme2/bg.gif",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme2/bg.gif",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1505959538721271812/UK52MvAZ_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1505959538721271812/UK52MvAZ_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/44906101/1647884431",
      profile_link_color: "CC3300",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "F7DA93",
      profile_text_color: "000000",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Thu Mar 31 13:12:17 +0000 2022",
    id: 1509518949997850600,
    id_str: "1509518949997850624",
    text: "Every day people die in #Ukraine because of the war that #russia started. You are aware of this, but your country i… https://t.co/I8q0DSA5co",
    truncated: true,
    entities: {
      hashtags: [
        {
          text: "Ukraine",
          indices: [24, 32],
        },
        {
          text: "russia",
          indices: [57, 64],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/I8q0DSA5co",
          expanded_url: "https://twitter.com/i/web/status/1509518949997850624",
          display_url: "twitter.com/i/web/status/1…",
          indices: [117, 140],
        },
      ],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1503326166144409600,
      id_str: "1503326166144409604",
      name: "Oleksandra",
      screen_name: "sashulya_bond",
      location: "Ukraine",
      description: "🇺🇦",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 3,
      friends_count: 41,
      listed_count: 0,
      created_at: "Mon Mar 14 11:04:42 +0000 2022",
      favourites_count: 131,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 258,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1503692544923865090/GducuW08_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1503692544923865090/GducuW08_normal.jpg",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
];
